packages:
  - "facilitator"
  - "servers/*"
  - "clients/*"
  - "fullstack/*"
  - "dynamic_agent"
  - "agent"
  - "mcp-embedded-wallet"
  - "mcp"
  - "discovery"
  - "fastset-merchant"
  - "../../typescript/packages/*"
